export const table_columns = [
  { Header: "Programa", accessor: "nombre" },
  { Header: "COD", accessor: "codigo" },
  { Header: "Inicio", accessor: "inicio" },
  { Header: "Coord.", accessor: "coordinador" },
  { Header: "Orientacion", accessor: "orientacion" },
  { Header: "Semestres", accessor: "duracion" },
  { Header: "Mat. Actual", accessor: "matriculados" },
  { Header: "Becados", accessor: "becados" },
  { Header: "Graduados", accessor: "graduados" },
  { Header: "Dictación", accessor: "dictacion" },
  /* { Header: "Costo Total", accessor: "arancel_total" }, */
  /*  { Header: "Acciones" ,accessor:'nombre',},  */
];
export const programas = [
  {
    nombre: "Doctorado en Astronomía y Cs. Planetarias",
    codigo: 3301,
    inicio: 2018,
    coordinador: "Lorenzo Morelli",
    orientacion: "Académica",
    duracion: 8,
    matriculados: 19,
    becados: 19,
    graduados: 0,
    dictacion: "regular",
    /*  arancel_total: 13200000, */
  },
  {
    nombre: "Magister en Estadística",
    codigo: 3305,
    inicio: 2019,
    coordinador: "Yolanda Gómez",
    orientacion: "Académica",
    duracion: 4,
    matriculados: 4,
    becados: 3,
    graduados: 1,
    dictacion: "regular",
  },
  {
    nombre: "Magister en Informática y Cs. de la Computación",
    codigo: 3201,
    inicio: 2013,
    coordinador: "John Castro",
    orientacion: "Académica",
    duracion: 4,
    matriculados: 4,
    becados: 4,
    graduados: 15,
    dictacion: "regular",
  },
  {
    nombre: "Magister en Ingeniería en Metalurgia",
    codigo: 3265,
    inicio: 2015,
    coordinador: "Alexis Guzmán",
    orientacion: "Académica",
    duracion: 4,
    matriculados: 11,
    becados: 10,
    graduados: 5,
    dictacion: "regular",
  },
  {
    nombre: "Magister en Metodologías de Investigación Cualitativas en Salud",
    codigo: 3289,
    inicio: 2018,
    coordinador: "Cory Duarte",
    orientacion: "Académica",
    duracion: 2,
    matriculados: 8,
    becados: 8,
    graduados: 5,
    dictacion: "regular",
  },
  {
    nombre: "Magister en Investigación Psicológica",
    codigo: 3291,
    inicio: 2018,
    coordinador: "Elva Morales",
    orientacion: "Académica",
    duracion: 4,
    matriculados: 8,
    becados: 8,
    graduados: 5,
    dictacion: "regular",
  },
];
